### ISSUE TITLE
Migrate rascsi data in easyinstall.sh

### ISSUE THREAD

**Issue by rdmark** [PiSCSI/piscsi#1020]
This is to break down the requirements for migrating user data and configurations when upgrading rascsi to piscsi.

- [x] systemd services -- rascsi, rascsi-web, rascsi-oled, rascsi-ctrlboard
- [x] ~/.config/rascsi
- [x] ~/.config/piscsi/rascsi_secret (maybe rename to simply call it `secret` -- it's use should be obvious from the context)
- [x] rascsi-web.key, rascsi-web.crt (maybe we can ignore these, since they get regenerated on the fly?)
- [x] User group rascsi (this might not need cleanup either)
- [x] Delete all old binaries
- [x] Delete all old manpages
- [x] Rename /etc/rsyslog.d/rascsi.conf
- [x] Rename /etc/network/interfaces.d/rascsi_bridge

**Comment by rdmark** [comment]
I can see two approaches here: Either have one function that we call every time that checks for the old files all at once and cleans them up, or we can have checks inline whenever we touch the relevant configurations.

**Comment by rdmark** [comment]
PR started at https://github.com/PiSCSI/piscsi/pull/1021

**Comment by akuker** [comment]
> User group rascsi (this might not need cleanup either)

Long term, it's probably better to rename everything to piscsi unless there is a compelling backwards compatibility concern. 

Or, are you thinking that easyinstall would just use the `rascsi` group name if it already exists? But if we're setting up something new, go with piscsi?

**Comment by rdmark** [comment]
@akuker After sleeping on it I agree the group and certs should be cleaned up too. Pushed a commit to the PR. (Still not fully tested though.)

**Comment by rdmark** [comment]
Alright, I've tested the PR now. Looks good so far.
