### ISSUE TITLE
Introduce a new logo for PiSCSI

### ISSUE THREAD

**Issue by rdmark** [PiSCSI/piscsi#1024]
After finalizing the new logo, use it for:
- [x] Web UI favicon / android / iOS icons (src/pwa/)
- [x] Web UI title bar logo (modern theme)
- [x] wiki graphics

**Comment by akuker** [comment]
Do we want to stick with the red panda? Or something else?

**Comment by rdmark** [comment]
I like the red panda idea.

**Comment by nucleogenic** [comment]
+1 for red panda.

**Comment by rdmark** [comment]
Lin83 @ Discord graciously drew a cute red panda logo for us. PR in https://github.com/PiSCSI/piscsi/pull/1074
