### ISSUE TITLE
Documentation 'Clone & build the PiSCSI software' needs update after project rename

### ISSUE THREAD

**Issue by hilburger** [PiSCSI/piscsi#1061]
Hi everybody! 

The 5th step in this [part](https://github.com/piscsi/piscsi/wiki/Setup-Instructions#clone--build-the-piscsi-software) needs an update. 

It says: 
```
sudo systemctl restart rsyslog
sudo systemctl enable rascsi # optional - start rascsi at boot
sudo systemctl start rascsi
sudo systemctl status rascsi
```

but should be: 
```
sudo systemctl restart rsyslog
sudo systemctl enable piscsi # optional - start piscsi at boot
sudo systemctl start piscsi
sudo systemctl status piscsi
```

So line 2-4 need rascsi changed to piscsi. 

Anyways it would be good for newbies like me to get explained ver early in the docs that rascsi has been renamed. 
Puzzled me pretty strongly in the beginning :)

Thanks!

**Comment by rdmark** [comment]
Good catch. I've updated this, and a handful other instances on the same wiki page.

If you find more outdated information, don't hesitate to edit the wiki yourself. It is a wiki after all!
