### ISSUE TITLE
Documentation 'Enable Authentication' needs update after project rename

### ISSUE THREAD

**Issue by hilburger** [PiSCSI/piscsi#1064]
Hi again! 

Installing my second PiSCSI I have not used the easyinstall script but tried the commands here: 
[https://github.com/PiSCSI/piscsi/wiki/Web-Interface#enable-authentication](https://github.com/PiSCSI/piscsi/wiki/Web-Interface#enable-authentication)

It is still using the group name rascsi and should be changed from this:
```
$ sudo groupadd rascsi
$ sudo usermod -a -G rascsi pi
```

to this: 
```
$ sudo groupadd piscsi
$ sudo usermod -a -G piscsi pi
```

Easyinstall script though works perfectly fine :)

**Comment by rdmark** [comment]
Thanks for reporting. This has now been updated.

If you find any other outdated info, don't hesitate to make edits yourself. It is a wiki after all. :)
