### ISSUE TITLE
Download/Upload configuration files?

### ISSUE THREAD

**Issue by Pacjunk** [PiSCSI/piscsi#1080]
# Feature request
Hi  - having recently transferred my images between cards due to OS upgrade, it would be nice if we could upload & download configuration files. We can already download properties files, but no way to upload them (short of uploading a ZIP containing the file). Would it be possible to:

1 - Add a button to download the selected configuration (json) file
2 - On the upload page, add upload of config files (json and properties) in addition to images & shared.

Thanks,

**Comment by rdmark** [comment]
Here ya go https://github.com/PiSCSI/piscsi/pull/1083

**Comment by Pacjunk** [comment]
Looks good. Thanks!
