### ISSUE TITLE
easyinstall: the piscsi stand-alone option messes up the systemd file

### ISSUE THREAD

**Issue by rdmark** [PiSCSI/piscsi#1150]
If you have a prior piscsi systemd file, and run the piscsi stand-alone installation script, it will append parameter to the startup line without taking existing ones into consideration, effectively breaking the systemd configuration.

**Comment by uweseimet** [comment]
@rdmark I'm just trying to get an overview on stale tickets. The problem addressed by this ticket appears to be quite serious, isn't it?

**Comment by rdmark** [comment]
Thanks for the reminder. Yes I need to fix this before the next release. It's pretty bad.

**Comment by rdmark** [comment]
I think this was fixed elsewhere already
