### ISSUE TITLE
Web UI: before_first_request is deprecated in Flask 2.3.x

### ISSUE THREAD

**Issue by rdmark** [PiSCSI/piscsi#1161]
Finding an alternative solution for the `before_first_request` decorator that was removed in Flask 2.3.0

https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0

> The app.before_first_request and bp.before_app_first_request decorators are removed.

Where the decorator was removed: https://github.com/pallets/flask/issues/4605

**Comment by rdmark** [comment]
Fixed with https://github.com/PiSCSI/piscsi/pull/1162

**Comment by ZulqarnainB** [comment]
what is an alternative of before_first_request in the latest version?

**Comment by rdmark** [comment]
@ZulqarnainB please see the PR I linked above for my solution. I used `before_request` with slightly different logic.

**Comment by FredySchaible** [comment]
@ZulqarnainB, you can also use **before_app_first_request** instead of **before_first_request**
