### ISSUE TITLE
Help identify GPIO pin stopping piscsi from working?

### ISSUE THREAD

**Issue by durosity** [PiSCSI/piscsi#1205]
Howdy!  

I have a couple of piSCSI units and a Pi 3a and Pi Zero W.  Both the piscsi boards work fine with the Zero, and used to work with the 3a until I had to replace the header pins due to damage.  Since then the piscsi will power up when used with the 3a but the host device won't see any scsi devices, so clearly I've broken one or more of the pin connections.  

The problem is I'm struggling to identify which one is causing it.  I've reflowed the solder connections and checked the continuity on the ones that I can see the traces for, but that's only a handful of pins.

Are there any logs that I could see on the pi that'd suggest where the problem is?

**Comment by uweseimet** [comment]
I just stumbled upon this issue and wonder why it has not been resolved yet. There are no such logs, and I doubt that it is technically possible to have any kind of logging for such an issue.
