### ISSUE TITLE
Web UI: Create a system administration page

### ISSUE THREAD

**Issue by rdmark** [PiSCSI/piscsi#1218]
As discussed in Discord: Break out more system admin-like options into a separate page.

Ideas:
- System restart / shutdown
- Log level and logging
- File sharing server management
- Macproxy status

Additionally, consider transitioning some functionality of easyinstall.sh into this administrative page.

**Comment by benjamink** [comment]
Link to start of conversation in Discord: https://discord.com/channels/749261651978748014/793579557197971488/1155171762259116103

**Comment by rdmark** [comment]
A first draft here https://github.com/PiSCSI/piscsi/pull/1222
