### ISSUE TITLE
Web server Error cannot import name 'url encode' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by fperdigon** [PiSCSI/piscsi#1244]
# Info

- Which version of Pi are you using: Rpi 3 8GB
- Which github revision of software: [v23.04.01](https://github.com/PiSCSI/piscsi/tree/v23.04.01)
- Which board version: 2.7
- Which computer is the PiSCSI connected to: Apple MAcintosh Classic

# Describe the issue
Error when starting the Web server.
When running `sudo journalctl -f`:
cannot import name 'url encode' from 'werkzeug.urls'
This happened because **flask==2.2.2** pulls the latest **werkzeug==3.0.0** lib that introduced this error.
Possible fix: adding **werkzeug==2.3.7** on [requirements.txt](https://github.com/PiSCSI/piscsi/blob/main/python/web/requirements.txt) file.
A better fix to avoid this from happening with other libraries will be: on each release freeze an entire environment that is known to work. `pip freeze > requirements.txt` when inside the environment

**Comment by rdmark** [comment]
Fixed in https://github.com/PiSCSI/piscsi/pull/1234
