### ISSUE TITLE
Create a new sub-folder for IDE setup files of general interest

### ISSUE THREAD

**Issue by uweseimet** [PiSCSI/piscsi#1325]
IDE-specific files of general interest, in particular formatting rules, should be added to the repository. A new top-level folder "ide_setup" should be used. The "cpp/.vscode" folder and launch_sudo script should also be moved there, in order not to force local preferences/setups onto other users with different needs. Actually, local settings like these should not be in the repository at all, but only files of general interest.
A README should be added to this folder, explaining the meaning/usage of these files.

- [x] Add Eclipse formatting rules
- [x] Remove user-specific files
- [x] Add README

**Comment by uweseimet** [comment]
@rdmark I suggest to remove the recently created .clang-format file, because it cannot be used for IDE configurations and also does not cover all the settings required.

**Comment by rdmark** [comment]
> @rdmark I suggest to remove the recently created .clang-format file, because it cannot be used for IDE configurations and also does not cover all the settings required.

Yes, please go ahead. Let's avoid multiple sets of files with overlapping purpose.

**Comment by uweseimet** [comment]
Just removed it.
