### ISSUE TITLE
scsictl: Execute serialized (protobuf format) commands

### ISSUE THREAD

**Issue by uweseimet** [PiSCSI/piscsi#1347]
scsictl shall be able to execute commands in serialized protobuf format. Also see #1348. The protobuf data would typically be stored in a file and scsictl would send these data directly to piscsi.

**Comment by rdmark** [comment]
Just out of curiosity, do you have particular use case in mind when built-in scsictl batching enables something that was impossible before?

If you have a shell environment you can script a batch of scsictl commands. And we also script batched calls to the protobuf interface.

Not to dispute that it could be a handy feature, but I wanted to check if this was the right thing to add complexity in scsictl for?

**Comment by uweseimet** [comment]
The part of being able to execute commands that are not in plain text but in serialized format is still required. I am going to update this ticket accordlingly.

**Comment by uweseimet** [comment]
Most likely not needed.
