### ISSUE TITLE
easysetup calls a non-existing method (likely due to a typo)

### ISSUE THREAD

**Issue by uweseimet** [PiSCSI/piscsi#1390]
```
echo "Hidden setup mode for running the pi-gen utility"
              echo "This shouldn't be used by normal users"
              sudoCache
```

I assume this should be "sudoCheck".

**Comment by rdmark** [comment]
Good catch. This is actually a typo for `cacheSudo`. It's the headless version of `sudoCheck`. I think it's there for the pi-gen script in particular, as a safeguard for when the process runs very long, that it doesn't prompt you unexpectedly for the password during the process.

**Comment by rdmark** [comment]
https://github.com/PiSCSI/piscsi/pull/1391
