### ISSUE TITLE
Please update compatibiity wiki - Akai S1000 and EMU ESI2000 tested and working with PiSCSI on PiZero2W

### ISSUE THREAD

**Issue by nebpor** [PiSCSI/piscsi#1475]
# Info

- Which version of Pi are you using: PiZero2W
- Which github revision of software: piscsi/v24.04.01 image used
- Which board version: PiSCSI / RaSCSI Adapter Board V2.3 B
- Which computer is the PiSCSI connected to: Akai S1000 Sampler and EMU ESI2000 Sampler
- Which OS you are using (output of 'lsb_release -a'): piscsi/v24.04.01 image used

# Describe the issue
PiSCSI works perfectly with Akai S1000 and EMU ESI2000 for both hard disk and CD-ROM drives - please update the Wiki for sampler compatibility thank you

**Comment by rdmark** [comment]
I have updated https://github.com/PiSCSI/piscsi/wiki/PiSCSI-for-Hardware-Samplers with this information, thank you!
