### ISSUE TITLE
API-based functionality for managing configurations for usage across multiple clients

### ISSUE THREAD

**Issue by bzeiss** [PiSCSI/piscsi#589]
Feature proposal

# Describe the issue

rascsi-web has functionality for loading, saving and deleting profiles. Those profiles provide preconfigured slot-to-image mappings that allows allows to quickly recall certain configurations. The current implementation is not interoperable with multiple clients, but is implemented directly in the web interface. It would probably be good if this functionality is moved into the core so that other client implementations (like the Android app or the hardware UI in development #382) can make shared use of these profiles (i.e. a profile is created with the web app and then loaded using the Android app or the hardware UI etc.) through the protobuf API.

**Comment by rdmark** [comment]
As an additional shortcoming of the current setup where rascsi-web is responsible for reading configurations, is the fact that the webapp has to be actually loaded in the user agent for configurations to be read.
