### ISSUE TITLE
Move os_integration folder one level up (it is not related to cpp)

### ISSUE THREAD

**Issue by uweseimet** [PiSCSI/piscsi#977]
The os_integration folder should be moved one level up. Currently it is in the cpp folder, but is not related to cpp.

**Comment by uweseimet** [comment]
@rdmark The data in this folder are used by easyinstall, aren't they?

**Comment by rdmark** [comment]
@uweseimet One of the files is, namely ```rascsi_bridge```. The easyinstall script copies it into ```/etc/network/interfaces.d/```. I wonder if there's an argument to be made for the Makefile script to do this instead?

**Comment by uweseimet** [comment]
@rdmark An additional Makefile target, or adding it to an appropriate existing target, should be fine.

By the way, my old SonarCloud long living feature branches still exists. Can you please remove them? I cannot do htat myself.

**Comment by rdmark** [comment]
@uweseimet I cleaned up the Sonar branch reports now. Also, I removed the filter that captured "feature_*" as long lived branches. To your point, feature branches are typically not long lived in this project.

**Comment by rdmark** [comment]
BTW, I think we should either remove ```cpp/os_integration/dhcpcd.conf.patch``` from the repo, or have the Makefile build target apply the patch in addition to copying rascsi_bridge. This is the one other part of the wired network bridge setup that easyinstall is currently carrying out. It is a disruptive change since it causes the eth0 IP address to change after a reboot.

**Comment by uweseimet** [comment]
@rdmark I don't know what's best here, but the Makefile should not contain any logic that is not directly related to the build/install process.

**Comment by uweseimet** [comment]
@rdmark One more remark: It might make sense to have more than one Makefile. A top-level Makefile and, where required) Makefiles in sub-folders. This is a common scenario. If you run make on top-level you build/install everything, if you run make in a sub-folder you only build/install a part.

**Comment by akuker** [comment]
Could we please put a hold on moving/renaming things until after I get the banana pi feature merged in? I realize that changes like this make things "better", but they're making it very difficult to keep my branches up to date. I'm spending a non-trivial amount of my time trying to keep my bpi branch up to date with non-functional changes. Its really hard to stay up to date when 50+ files change every few days.

Could we please focus on features/tickets that provide an immediate customer benefit for now?

**Comment by akuker** [comment]
As a side note, I'd be glad to get some help with the Banana Pi functionality :)

**Comment by rdmark** [comment]
I agree that there's no rush in making changes here. It's just cleanup for a more logical dir tree structure. We could revisit this as a fast follow after the next release.

**Comment by rdmark** [comment]
Since there's a lull in activity now, let's address the original request: https://github.com/PiSCSI/piscsi/pull/1085
